name: Selenium Tests

on:
  schedule:
    - cron: '0 3,11,17 * * *'  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas

      # - name: Run AQA November 2018 tests
      #   run: pytest test_AQANovember2018Answers.py --tb=short --junitxml=results.xml

      # - name: Run AQA June 2018 tests
      #   run: pytest test_AQAJune2018Answers.py --tb=short --junitxml=results.xml

      # - name: Run AQA November 2017 tests
      #   run: pytest test_AQANovember2017.py --tb=short --junitxml=results.xml

      # - name: Run AQA June 2017 tests
      #   run: pytest test_AQAJune2017.py  --tb=short --junitxml=results.xml

      # - name: Run AQA Specimen tests
      #   run: pytest test_AQASpecimenAnswers.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2018 Mark scheme tests
      #   run: pytest test_EdexcelNovember2018.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2018 Model Answers tests
      #   run: pytest test_EdexcelNovember2018ModelAnswers.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2017 Model Answers tests
      #   run: pytest test_EdexcelNovember2017ModelAnswers.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2017 Mark scheme tests
      #   run: pytest test_EdexcelNovember2017Marksscheme.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2017 Mark scheme tests
      #   run: pytest test_EdexcelJune2017Markschemes.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2016 Model answers tests
      #   run: pytest test_EdexcelJune2016ModelAnswers.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2016 Mark scheme tests
      #   run: pytest test_EdexcelJune2016Markscheme.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2015 Mark scheme tests
      #   run: pytest test_EdexcelNovember2015MarkSchemes.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2015 Mark scheme tests
      #   run: pytest test_EdexcelJune2015MarkScheme.py   --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2014 Mark scheme tests
      #   run: pytest test_EdexcelNovember2014MarkScheme.py   --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2014 Mark scheme tests
      #   run: pytest test_EdexcelJune2014MarkScheme.py   --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2013 Mark scheme tests
      #   run: pytest test_EdexcelNovember2013MarkScheme.py   --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2013 Mark scheme tests
      #   run: pytest test_EdexcelJune2013MarkScheme.py   --tb=short --junitxml=results.xml

      # - name: Run Edexcel March 2013 Mark scheme tests
      #   run: pytest test_EdexcelMarch2013MarkScheme.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2012 Mark scheme tests
      #   run: pytest test_EdexcelNovember2012MarkScheme.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2012 Mark scheme tests
      #   run: pytest test_EdexcelJune2012MarkScheme.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel November 2011 Mark scheme tests
      #   run: pytest test_EdexcelNovember2011Markscheme.py  --tb=short --junitxml=results.xml

      # - name: Run Edexcel June 2011 Mark scheme tests
      #   run: pytest test_EdexcelJune2011Markscheme.py  --tb=short --junitxml=results.xml

      - name: Run Edexcel November 2010 Mark scheme tests
        run: pytest test_EdexcelNovember2010MarkScheme.py  --tb=short --junitxml=results.xml
            
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png


      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
